"""Test

Revision ID: 71a171b6a454
Revises: 3e6f12d7831c
Create Date: 2022-10-06 22:00:15.381642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71a171b6a454'
down_revision = '3e6f12d7831c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search',
    sa.Column('search_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('search_id')
    )
    op.create_index(op.f('ix_search_search_id'), 'search', ['search_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_search_id'), table_name='search')
    op.drop_table('search')
    # ### end Alembic commands ###
